# Generated by Django 4.2.3 on 2023-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManipulatedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='media/')),
                ('enhanced_image', models.ImageField(upload_to='media/')),
                ('edge_detected_image', models.ImageField(upload_to='media/')),
                ('grayscale_image', models.ImageField(upload_to='media/')),
                ('green_channel_image', models.ImageField(upload_to='media/')),
                ('artistic_image', models.ImageField(upload_to='media/')),
                ('colored_image', models.ImageField(upload_to='media/')),
                ('sharpened_image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
